// Run: node pc/check-ui.cjs. Checks language switching without translating user data.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const pairs = JSON.parse(fs.readFileSync(path.join(__dirname, '../app/src/main/assets/ui-translations.json'), 'utf8'));
const source = fs.readFileSync(path.join(__dirname, 'i18n.js'), 'utf8').replace(/^import .*;\n/, '').replace('export function', 'function');
const context = vm.createContext({ pairs });
vm.runInContext(source, context);
assert.equal(context.translate('仓库定位系统', 'ja'), '倉庫位置管理システム');
assert.equal(context.translate('倉庫位置管理システム', 'zh'), '仓库定位系统');
assert.equal(context.translate('个商品', 'zh'), '个商品');
assert.equal(context.translate('已到期', 'ja'), '期限終了');
assert.equal(context.translate('等待手机控制桥接', 'ja'), 'スマホ中継端末を待っています');
assert.equal(context.translate('设置待机间隔', 'ja'), '待受間隔設定');
assert.equal(context.translate('+ エリア追加', 'zh'), '+ 添加区域');
assert.equal(context.translate('连接失败：HOST', 'ja'), '接続失敗：HOST');
const vue = fs.readFileSync(path.join(__dirname, 'WarehouseConsole.vue'), 'utf8');
assert.ok(vue.includes('{{ w.name }}') && vue.includes('{{ p.name }}'), 'User-entered names must remain unchanged');
assert.ok(!vue.includes('西柚'), 'Console title must not carry the old brand');
console.log('UI language checks passed (Chinese / Japanese, dynamic messages, unchanged catalog names).');
// Exercise the actual component methods: finding never alters the viewport;
// a failed batch item stays selected while successful items remain active.
const componentScript = vue.split('<script>')[1].split('</script>')[0].replace(/^import .*;\n/gm, '').replace('export default', 'globalThis.component =');
const uiContext = vm.createContext({ crypto: require('node:crypto').webcrypto, location: { search: '', origin: 'http://localhost', port: '8090' }, URLSearchParams, localStorage: { getItem: () => null }, translate: context.translate });
vm.runInContext(componentScript, uiContext);
const component = uiContext.component;
const ui = component.data();
Object.entries(component.methods).forEach(([key, method]) => ui[key] = method.bind(ui));
Object.entries(component.computed).forEach(([key, get]) => Object.defineProperty(ui, key, { get: get.bind(ui) }));
ui.state.warehouses = [{ id: 'wh',name:'仓库一' }]; ui.state.areas=[{id:'area',warehouseId:'wh',name:'区域一'}]; ui.state.maps = [{ id: 'm', warehouseId: 'wh' }];
ui.state.products = [{ id: 'a', warehouseId: 'wh', beaconCode: '1' }, { id: 'b', warehouseId: 'wh', beaconCode: '2' }];
ui.state.placements = ui.state.products.map((p, i) => ({id:'point-'+i,kind:'product', entityId:p.id, mapId:'m', x:0.2+i*0.5,y:0.4}));
ui.mapId='m'; ui.warehouseId='wh'; ui.zoom=1.25; ui.pan={x:10,y:20};
ui.$Message={info:()=>{},error:()=>{}};
ui.$refs={viewport:{clientWidth:800,clientHeight:400,querySelector:()=>({clientWidth:800,clientHeight:500})}}; ui.$nextTick=fn=>fn();
ui.focus(ui.state.products[0],false);
assert.equal(ui.zoom,1.25); assert.equal(ui.pan.x,10); assert.equal(ui.pan.y,20);
ui.checkVisible(true); assert.equal(ui.checkedProducts.length,2);
const calls=[];
ui.api=async (route,body)=>{ calls.push({route,body}); return { id:'run-1', items:[{productId:'a',taskId:'task-a'}, {productId:'b',error:'fixture failure'}] }; };
ui.refresh=async()=>{};
(async()=>{
 await ui.findSelected();
 assert.equal(calls.length,1); assert.equal(calls[0].route,'find-batch'); assert.equal(calls[0].body.productIds.length,2); assert.equal(ui.checkedProducts.length,1); assert.equal(ui.checkedProducts[0].id,'b');
 assert.equal(ui.zoom,1.25); assert.equal(ui.pan.x,10);
 ui.state.tasks=[{id:'ta',warehouseId:'wh',status:'sent'},{id:'tb',warehouseId:'wh',status:'queued'}];
 calls.length=0; ui.api=async(route,body)=>{calls.push({route,body}); return {};};
 await ui.stopAll(); assert.equal(calls.length,2);
 assert.deepEqual(calls.map(c=>c.route),['tasks/ta/stop','tasks/tb/stop']);
 ui.state.taskRuns=[{id:'run-1',createdAt:1,origin:'pc',items:[{taskId:'ta',name:'a',productId:'a',warehouseId:'wh'},{taskId:'tb',name:'b',productId:'b',warehouseId:'wh'}]}];
 assert.equal(ui.taskRuns.length,1); assert.equal(ui.taskRuns[0].items.length,2);
 assert.equal(ui.runStatus(ui.taskRuns[0]),'进行中');
 ui.state.tasks[0].status='failed'; assert.equal(ui.runStatus(ui.taskRuns[0]),'存在异常');
 ui.state.tasks.forEach(t=>t.status='stopped'); assert.equal(ui.runStatus(ui.taskRuns[0]),'已停止');
 ui.focus(ui.state.products[0]); assert.equal(ui.zoom,1.6);
 assert.equal(ui.pan.x + 0.2*800*ui.zoom,400); assert.equal(ui.pan.y + 0.4*500*ui.zoom,200);
 ui.setZoom(ui.zoom/1.25); assert.equal(ui.zoom,1.28);
 assert.equal(ui.pan.x + 0.2*800*ui.zoom,400);
 ui.resetView(); ui.query='2'; ui.searchLocation(); assert.equal(ui.selected,'product:b'); assert.equal(ui.zoom,1.6);
 ui.setZoom(0.25); assert.equal(ui.zoom,0.25); ui.resetView(); assert.equal(ui.zoom,1);
 ui.state.tasks.forEach(t=>t.status='queued'); calls.length=0; await ui.stopRun(ui.taskRuns[0]); assert.equal(calls.length,2);
 ui.state.products[0].areaId='area'; ui.state.products[0].shelf='R-01';
 ui.query=''; assert.equal(ui.productTableRows[0].warehouseArea,'仓库一 / 区域一'); assert.equal(ui.productTableRows[0].shelfLabel,'R-01');
 assert.ok(!ui.localizedProductColumns.some(c=>c.title==='操作'));
 ui.popupMarker=''; ui.hoveredMarker=''; ui.mobile=true; const marker=ui.markers[0]; ui.moved=false; ui.markerClick(marker); assert.equal(ui.bubble.label,ui.state.products[0].name); assert.equal(ui.bubble.shelf,'R-01');
 ui.mapClick({}); assert.equal(ui.bubble,undefined);
 ui.mobile=false; ui.hoverMarker(marker); assert.equal(ui.bubble.label,ui.state.products[0].name); ui.hoveredMarker=''; assert.equal(ui.bubble,undefined);
 ui.focus(ui.state.products[0]); assert.equal(ui.focusedProduct,'a'); assert.equal(ui.popupMarker,marker.id);
 ui.state.taskRuns=[]; ui.state.tasks=Array.from({length:6},(_,i)=>({id:'history-'+i,status:'stopped',warehouseId:'wh',createdAt:i}));
 assert.equal(ui.taskSections[0].runs.length,3); assert.equal(ui.taskSections[1].runs.length,3);
 ui.state.tasks[0].status='queued'; assert.equal(ui.taskSections[0].runs.length,4); assert.equal(ui.taskSections[1].runs.length,2);
 console.log('Finding checks passed (unchanged viewport, multiple selection, partial retry, independent stop).');
})().catch(e=>{console.error(e);process.exitCode=1;});
